# Generated by Django 4.1.5 on 2023-01-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_company_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
