# Generated by Django 4.1.5 on 2023-01-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_company_app', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
