# Generated by Django 4.1.5 on 2023-01-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_company_app', '0014_alter_post_photografy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photografy',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
